stages:
  - validate
  - security

dockerx:
  stage: validate
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/dockerx:latest docker --version
    - docker run --rm ghcr.io/tooark/dockerx:latest docker buildx version

aws_cli:
  stage: validate
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/aws-cli:latest aws --version
    - docker run --rm ghcr.io/tooark/aws-cli:latest kubectl version --client

gcloud_cli:
  stage: validate
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/gcloud-cli:latest gcloud --version
    - docker run --rm ghcr.io/tooark/gcloud-cli:latest kubectl version --client

terraform:
  stage: validate
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/terraform:latest terraform version

terraform_aws:
  stage: validate
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/terraform-aws:latest terraform version
    - docker run --rm ghcr.io/tooark/terraform-aws:latest aws --version

terraform_gcloud:
  stage: validate
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/terraform-gcloud:latest terraform version
    - docker run --rm ghcr.io/tooark/terraform-gcloud:latest gcloud --version

terraform_aws_gcloud:
  stage: validate
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/terraform-aws-gcloud:latest terraform version
    - docker run --rm ghcr.io/tooark/terraform-aws-gcloud:latest aws --version
    - docker run --rm ghcr.io/tooark/terraform-aws-gcloud:latest gcloud --version

sonar_scanner:
  stage: security
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm ghcr.io/tooark/sonar-scanner:latest sonar-scanner --version
    - docker run --rm ghcr.io/tooark/sonar-scanner:latest java -version

trivy_hadolint:
  stage: security
  image: ghcr.io/tooark/trivy-hadolint:latest
  cache:
    key: trivy-db
    paths:
      - .cache/trivy
  variables:
    TRIVY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/trivy"
    REPORT_DIR: "$CI_PROJECT_DIR/scan-reports"
    TRIVY_SEVERITY: "HIGH,CRITICAL"
    TRIVY_SEVERITY_FAIL: "HIGH,CRITICAL"
    TRIVY_IGNORE_UNFIXED: "true"
    HADOLINT_FAILURE_LEVEL: "warning"
  script:
    - ark-tools version
    - ark-tools image-scan nginx:latest
    - ark-tools container nginx:latest --path "$CI_PROJECT_DIR"
  artifacts:
    when: always
    paths:
      - scan-reports/
    expire_in: 7 days
